### ISSUE TITLE
how to prevent testcafeLighthouseAudit from rendering new page to test the url 

### ISSUE THREAD

**Issue by essaabouasali-code** [abhinaba-ghosh/testcafe-lighthouse#21] opened 2020-10-15 00:05 UTC

**Comment by abhinaba-ghosh** [comment] 2020-10-15 11:02
duplicate of https://github.com/abhinaba-ghosh/testcafe-lighthouse/issues/22

**Closed** 2020-10-15 11:02 UTC
Labels: feature_request
